language: elixir

elixir:
  - 1.4.2

otp_release:
  - 19.3

sudo: required

services:
  - docker

before_install:
  - docker pull eventstore/eventstore

before_script:
  - socat TCP-LISTEN:2375,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock &
